// NOTE: This is a good-faith starting template, NOT legal advice. Have a
// professional review it, and set the real contact email + effective date
// before submitting to the App Store / Google Play.
import React from "react";
import { View, Text, StyleSheet, ScrollView, Pressable } from "react-native";
import { useRouter } from "expo-router";
import { StatusBar } from "expo-status-bar";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { Colors } from "../constants/colors";

const EFFECTIVE_DATE = "July 2026";
const CONTACT_EMAIL = "support@hearth.app"; // TODO: replace with your real address

function Section({ title, children }: { title: string; children: string }) {
  return (
    <View style={styles.section}>
      <Text style={styles.h2}>{title}</Text>
      <Text style={styles.body}>{children}</Text>
    </View>
  );
}

export default function Terms() {
  const router = useRouter();
  return (
    <View style={styles.root}>
      <StatusBar style="light" />
      <SafeAreaView style={styles.safe} edges={["top"]}>
        <View style={styles.header}>
          <Pressable onPress={() => router.back()} hitSlop={12}>
            <Ionicons name="arrow-back" size={24} color={Colors.accent.light} />
          </Pressable>
          <Text style={styles.headerTitle}>Terms of Service</Text>
          <View style={{ width: 24 }} />
        </View>
        <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
          <Text style={styles.effective}>Effective {EFFECTIVE_DATE}</Text>

          <Section title="Acceptance">
            {"By using Hearth, you agree to these terms. If you do not agree, please do not use the app."}
          </Section>

          <Section title="What Hearth is">
            {"Hearth is a self-reflection and wellbeing companion. It is not therapy, counseling, medical care, or a crisis service, and Ember is an AI, not a licensed professional."}
          </Section>

          <Section title="Not a substitute for professional help">
            {"Nothing in Hearth should be taken as medical, psychological, or professional advice. Always seek a qualified professional for health concerns. If you are in crisis, contact Befrienders Malaysia at 03-7627 2929 or your local emergency services."}
          </Section>

          <Section title="Eligibility">
            {"You must be at least 13 years old (or the minimum age in your country) to use Hearth."}
          </Section>

          <Section title="Your account & content">
            {"You are responsible for keeping your login secure and for the content you enter. Your reflections and conversations are private to your account."}
          </Section>

          <Section title="Acceptable use">
            {"Do not misuse the app, attempt to disrupt it, or use it for anything unlawful or harmful to yourself or others."}
          </Section>

          <Section title="AI limitations">
            {"Ember's responses are generated by AI and may be inaccurate or incomplete. Use your own judgment and do not rely on them for important decisions."}
          </Section>

          <Section title="No warranty">
            {"Hearth is provided “as is” without warranties of any kind. To the extent permitted by law, we are not liable for any damages arising from your use of the app."}
          </Section>

          <Section title="Termination">
            {"You may stop using Hearth at any time. We may suspend access if these terms are violated."}
          </Section>

          <Section title="Contact">
            {`Questions about these terms? Email ${CONTACT_EMAIL}.`}
          </Section>
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: Colors.bg.primary },
  safe: { flex: 1 },
  header: {
    height: 56,
    paddingHorizontal: 24,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    color: Colors.text.primary,
    fontSize: 18,
    fontFamily: "Literata_600SemiBold",
  },
  content: { paddingHorizontal: 24, paddingTop: 8, paddingBottom: 48 },
  effective: {
    color: Colors.text.muted,
    fontSize: 13,
    fontFamily: "DMSans_400Regular",
    marginBottom: 20,
  },
  section: { marginBottom: 24 },
  h2: {
    color: Colors.accent.light,
    fontSize: 17,
    fontFamily: "Literata_600SemiBold",
    marginBottom: 8,
  },
  body: {
    color: Colors.text.secondary,
    fontSize: 15,
    lineHeight: 24,
    fontFamily: "DMSans_400Regular",
  },
});
